#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

PROG=/usr/bin/poold
DB_PATH=/var/lib/poold/poold.db
LISTEN_ADDR=127.0.0.1:8090
POOL_ADDR=127.0.0.1:8990

start_service() {
	mkdir -p /var/lib/poold

	procd_open_instance
	procd_set_param command "$PROG" \
		-listen "${POOLD_LISTEN_ADDR:-$LISTEN_ADDR}" \
		-pool "${POOLD_POOL_ADDR:-$POOL_ADDR}" \
		-db "${POOLD_DB_PATH:-$DB_PATH}"
	procd_set_param env \
		POOLD_ENV=openwrt \
		POOLD_TOKEN="${POOLD_TOKEN}" \
		POOLD_TIMEZONE="${POOLD_TIMEZONE:-Europe/Berlin}" \
		POOLD_HEATING_RATE_C_PER_HOUR="${POOLD_HEATING_RATE_C_PER_HOUR:-0.75}" \
		POOLD_READINESS_BUFFER="${POOLD_READINESS_BUFFER:-30m}"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
